const fs = require('fs');
const path = require('path');

// Helper to create domain structure
function createDomain(id, name, icon, color, description, levels) {
  return { id, name, icon, color, description, levels };
}

// AI/ML Domain with 60 questions
const aiml = createDomain(
  'ai-ml',
  'AI/ML Research',
  '🤖',
  '#06b6d4',
  'Neural networks, transformers, diffusion models, and cutting-edge ML research',
  {
    beginner: {
      name: 'Beginner',
      description: 'Fundamentals of neural networks and machine learning',
      questions: [
        {id:'ai-b1',type:'multiple-choice',question:'What is a neuron in a neural network?',options:['A biological cell','A computational unit that takes inputs, applies weights, and produces an output','A type of activation function','A layer in the network'],correct:1,explanation:'An artificial neuron is a computational unit inspired by biological neurons. It takes weighted inputs, sums them, and applies an activation function.',xp:10},
        {id:'ai-b2',type:'multiple-choice',question:'What does ReLU (Rectified Linear Unit) do?',options:['Returns max(0, x)','Returns a value between 0 and 1','Returns a value between -1 and 1','Returns the square of the input'],correct:0,explanation:'ReLU is f(x) = max(0, x). Simple, efficient, helps avoid vanishing gradients.',xp:10},
        {id:'ai-b3',type:'multiple-choice',question:'What is backpropagation?',options:['A forward pass','An algorithm for computing gradients of loss with respect to weights','A type of architecture','A preprocessing technique'],correct:1,explanation:'Backpropagation uses chain rule to compute gradients layer by layer, backwards from output.',xp:10},
        {id:'ai-b4',type:'multiple-choice',question:'What is the purpose of a loss function?',options:['To activate neurons','To measure how wrong predictions are','To normalize data','To split data into batches'],correct:1,explanation:'Loss function quantifies prediction error. Training minimizes loss by adjusting weights.',xp:10},
        {id:'ai-b5',type:'multiple-choice',question:'What is overfitting?',options:['Model is too simple','Model memorizes training data but fails on new data','Learning rate is too high','Model trains too quickly'],correct:1,explanation:'Overfitting: model learns noise from training data that doesnt generalize.',xp:10},
        {id:'ai-b6',type:'multiple-choice',question:'What is dropout?',options:['Speed up training','Randomly disable neurons to prevent overfitting','Normalize activations','Initialize weights'],correct:1,explanation:'Dropout randomly zeros neurons during training, forcing robust feature learning.',xp:10},
        {id:'ai-b7',type:'multiple-choice',question:'What does SGD stand for?',options:['Standard Gradient Descent','Stochastic Gradient Descent','Smooth Gradient Distribution','Sequential Gradient Deployment'],correct:1,explanation:'Stochastic Gradient Descent updates with random batches, faster and helps escape local minima.',xp:10},
        {id:'ai-b8',type:'multiple-choice',question:'Convolutional layers are primarily used for?',options:['Text processing','Image processing and feature extraction','Time series','Graph analysis'],correct:1,explanation:'Convolutional layers detect local patterns like edges using sliding filters.',xp:10},
        {id:'ai-b9',type:'multiple-choice',question:'What is the vanishing gradient problem?',options:['Gradients too large','Gradients become extremely small, preventing learning in early layers','Learning rate decreases','Neurons stop firing'],correct:1,explanation:'Gradients shrink exponentially through deep layers with certain activations.',xp:10},
        {id:'ai-b10',type:'multiple-choice',question:'What is batch normalization?',options:['Normalizing input data','Normalizing activations within mini-batches during training','Adjusting batch size','Removing outliers'],correct:1,explanation:'Batch norm stabilizes training, allows higher learning rates, acts as regularization.',xp:10},
        {id:'ai-b11',type:'multiple-choice',question:'What is transfer learning?',options:['Moving data','Using pre-trained model on related task to boost performance on new task','Transferring weights randomly','Converting formats'],correct:1,explanation:'Transfer learning leverages knowledge from large datasets by fine-tuning on specific tasks.',xp:10},
        {id:'ai-b12',type:'multiple-choice',question:'What is softmax used for?',options:['Regularization','Converting raw scores into probabilities for multi-class classification','Feature extraction','Gradient clipping'],correct:1,explanation:'Softmax transforms logits into probability distribution summing to 1.',xp:10},
        {id:'ai-b13',type:'multiple-choice',question:'What is an epoch?',options:['One weight update','One complete pass through entire training dataset','One batch','One layer'],correct:1,explanation:'An epoch means model has seen every training example once.',xp:10},
        {id:'ai-b14',type:'multiple-choice',question:'What is learning rate?',options:['Data processing speed','Step size for weight updates during gradient descent','Computer speed','Epochs per second'],correct:1,explanation:'Learning rate controls weight change size. Too high: instability. Too low: slow training.',xp:10},
        {id:'ai-b15',type:'multiple-choice',question:'What is validation set for?',options:['Final testing','Tuning hyperparameters and monitoring overfitting during training','Training the model','Data augmentation'],correct:1,explanation:'Validation set evaluates performance and tunes hyperparameters without touching test set.',xp:10},
        {id:'ai-b16',type:'multiple-choice',question:'What does CNN stand for?',options:['Convolutional Neural Network','Computational Neural Network','Complex Neural Network','Cascading Neural Network'],correct:0,explanation:'CNNs use convolutions to learn hierarchical spatial features, revolutionizing vision.',xp:10},
        {id:'ai-b17',type:'multiple-choice',question:'What is data augmentation?',options:['Adding layers','Creating modified training data (rotations, crops) to increase dataset size','Increasing batch size','Adding noise to weights'],correct:1,explanation:'Data augmentation artificially expands training set with transformations.',xp:10},
        {id:'ai-b18',type:'multiple-choice',question:'What is gradient descent?',options:['Data collection','Optimization algorithm moving in direction of steepest loss decrease','Type of network','Regularization technique'],correct:1,explanation:'Gradient descent computes loss gradient and updates parameters to minimize error.',xp:10},
        {id:'ai-b19',type:'multiple-choice',question:'What is a hyperparameter?',options:['Parameter learned during training','Configuration setting chosen before training (learning rate, batch size)','Final output','Activation function'],correct:1,explanation:'Hyperparameters control learning process, unlike model parameters learned from data.',xp:10},
        {id:'ai-b20',type:'multiple-choice',question:'What is test set for?',options:['Training','Unbiased evaluation of final model performance','Tuning hyperparameters','Augmenting data'],correct:1,explanation:'Test set provides final assessment on truly unseen data.',xp:10}
      ]
    },
    intermediate: {
      name: 'Intermediate',
      description: 'Advanced architectures and training techniques',
      questions: [
        {id:'ai-i1',type:'multiple-choice',question:'Key innovation of Transformer architecture?',options:['CNNs for NLP','Self-attention allowing parallel processing of sequences','Recurrent connections','Dropout'],correct:1,explanation:'Transformers use self-attention to weigh importance of positions, enabling parallelization.',xp:15},
        {id:'ai-i2',type:'multiple-choice',question:'What does BERT stand for?',options:['Bidirectional Encoder Representations from Transformers','Basic Encoding Retrieval Transformer','Bidirectional Embedding Recurrent Transformer','Binary Encoded Representation'],correct:0,explanation:'BERT pre-trains bidirectional representations by masking words, revolutionizing NLP.',xp:15},
        {id:'ai-i3',type:'multiple-choice',question:'Purpose of positional encoding in Transformers?',options:['Reduce size','Inject position info since attention has no inherent order','Normalize inputs','Prevent overfitting'],correct:1,explanation:'Self-attention is permutation-invariant, so positional encodings add sequential information.',xp:15},
        {id:'ai-i4',type:'multiple-choice',question:'What is a GAN?',options:['Type of CNN','Generator and discriminator competing: generator creates fake data, discriminator detects it','Reinforcement learning','Attention mechanism'],correct:1,explanation:'GANs train through adversarial competition: generator learns to fool discriminator.',xp:15},
        {id:'ai-i5',type:'multiple-choice',question:'What is attention computing?',options:['Random weights','Weighted sums of values based on query-key similarity','Convolutional filters','Gradient magnitudes'],correct:1,explanation:'Attention computes relevance (query·key), softmax, then weights values for dynamic focus.',xp:15},
        {id:'ai-i6',type:'multiple-choice',question:'ResNets key contribution?',options:['Using attention','Skip connections enabling very deep networks','Removing pooling','Only linear activations'],correct:1,explanation:'ResNet skip connections allow gradients to flow directly, solving degradation in deep networks.',xp:15},
        {id:'ai-i7',type:'multiple-choice',question:'Vanishing gradient in RNNs?',options:['Gradients become zero','Gradients decay exponentially over many time steps, preventing long-term learning','Gradients explode','Gradients oscillate'],correct:1,explanation:'In long sequences, gradients shrink exponentially, making RNNs forget long-term dependencies.',xp:15},
        {id:'ai-i8',type:'multiple-choice',question:'What do LSTMs add?',options:['Convolutional layers','Gating mechanisms (forget, input, output gates) to control information flow','Attention heads','Residual connections'],correct:1,explanation:'LSTM gates selectively remember/forget, enabling long-term dependency learning.',xp:15},
        {id:'ai-i9',type:'multiple-choice',question:'Transfer learning in LLMs?',options:['Copying weights exactly','Pre-training on large corpus, then fine-tuning on specific task','Training multiple models','Transferring data'],correct:1,explanation:'LLMs learn general language from massive pre-training, then adapt with little task data.',xp:15},
        {id:'ai-i10',type:'multiple-choice',question:'Purpose of layer normalization?',options:['Normalizing across batch','Normalizing across features for each sample independently','Removing layers','Adding noise'],correct:1,explanation:'Layer norm normalizes activations across features per sample, stabilizing RNNs/Transformers.',xp:15},
        {id:'ai-i11',type:'multiple-choice',question:'Key idea behind autoencoders?',options:['Supervised classification','Unsupervised learning by compressing into latent representation then reconstructing','Adversarial training','Reinforcement learning'],correct:1,explanation:'Autoencoders learn efficient representations through bottleneck, minimizing reconstruction error.',xp:15},
        {id:'ai-i12',type:'multiple-choice',question:'What does GPT stand for?',options:['General Pre-trained Transformer','Generative Pre-trained Transformer','Gradient Propagation Technique','Gated Positional Transformer'],correct:1,explanation:'GPT models are autoregressive, trained to predict next token, enabling generation and few-shot learning.',xp:15},
        {id:'ai-i13',type:'multiple-choice',question:'Purpose of softmax temperature?',options:['Training speed','Controlling randomness of probability distributions (higher = more random)','Adjusting learning rate','Setting batch size'],correct:1,explanation:'Temperature scales logits: T>1 flattens (random), T<1 sharpens (confident).',xp:15},
        {id:'ai-i14',type:'multiple-choice',question:'What is knowledge distillation?',options:['Removing knowledge','Training smaller student model to mimic larger teacher outputs','Extracting facts','Compressing weights'],correct:1,explanation:'Distillation transfers knowledge from complex to simple models via soft predictions.',xp:15},
        {id:'ai-i15',type:'multiple-choice',question:'Purpose of multi-head attention?',options:['Training multiple models','Learning different representation subspaces by running multiple attention in parallel','Multiple datasets','Stacking layers'],correct:1,explanation:'Multi-head attention attends to different aspects simultaneously, capturing richer relationships.',xp:15},
        {id:'ai-i16',type:'multiple-choice',question:'What is curriculum learning?',options:['Teaching multiple subjects','Training on progressively harder examples, starting with easier ones','Fixed training order','Random sampling'],correct:1,explanation:'Curriculum learning presents simpler examples first, often improving convergence and generalization.',xp:15},
        {id:'ai-i17',type:'multiple-choice',question:'What is contrastive learning?',options:['Comparing brightness','Learning representations by pulling similar examples together, pushing dissimilar apart','Training adversarially','Using negative weights'],correct:1,explanation:'Contrastive learning (SimCLR) makes augmented views of same image close, different images far.',xp:15},
        {id:'ai-i18',type:'multiple-choice',question:'What is CLIP?',options:['Video editing tool','Vision-language model trained to align image and text embeddings','Text-only model','Audio model'],correct:1,explanation:'CLIP learns joint embeddings via contrastive learning, enabling zero-shot classification.',xp:15},
        {id:'ai-i19',type:'multiple-choice',question:'What is LoRA (parameter-efficient fine-tuning)?',options:['Training fewer epochs','Updating only small number of additional parameters while freezing base model','Using smaller batches','Reducing model size'],correct:1,explanation:'LoRA adds trainable low-rank matrices to frozen weights, enabling efficient adaptation.',xp:15},
        {id:'ai-i20',type:'multiple-choice',question:'Difference: encoder-only, decoder-only, encoder-decoder?',options:['Number of layers','Encoder-only (BERT) for understanding, decoder-only (GPT) for generation, encoder-decoder (T5) for seq2seq','Training time','Model size'],correct:1,explanation:'Architecture depends on task: encoders for classification, decoders for generation, both for translation.',xp:15}
      ]
    },
    advanced: {
      name: 'Advanced',
      description: 'Research-level understanding',
      questions: [
        {id:'ai-a1',type:'multiple-choice',question:'Key innovation in diffusion models?',options:['Using GANs','Learning to reverse gradual noising by predicting noise at each step','Using RL','Adversarial training'],correct:1,explanation:'Diffusion models denoise step-by-step, reversing Markov chain of Gaussian noise.',xp:20},
        {id:'ai-a2',type:'multiple-choice',question:'Reparameterization trick in VAEs?',options:['Changing activations','Sampling via z=μ+σ⊙ε where ε~N(0,1), making sampling differentiable','Adjusting LR','Modifying architecture'],correct:1,explanation:'Reparameterization moves randomness outside learned parameters, allowing gradient flow.',xp:20},
        {id:'ai-a3',type:'multiple-choice',question:'What is ELBO in VAEs?',options:['Regularization term','Objective: reconstruction loss + KL divergence, lower-bounding log-likelihood','Sampling strategy','Activation function'],correct:1,explanation:'ELBO balances reconstruction with regularization (KL to prior), tractable VAE training.',xp:20},
        {id:'ai-a4',type:'multiple-choice',question:'What is Mixture of Experts?',options:['Training multiple models','Layer with sub-networks where gating routes inputs to specific experts','Ensemble learning','Multi-task learning'],correct:1,explanation:'MoE increases capacity efficiently by activating subset of parameters per token.',xp:20},
        {id:'ai-a5',type:'multiple-choice',question:'AlphaGos key insight?',options:['Pure brute force','Combining neural network value/policy evaluation with MCTS for strategic planning','Only supervised learning','Random play'],correct:1,explanation:'AlphaGo uses policy/value networks to guide MCTS for superhuman Go.',xp:20},
        {id:'ai-a6',type:'multiple-choice',question:'Purpose of reward modeling in RLHF?',options:['Replacing humans','Learning reward function from human preferences to guide RL fine-tuning','Generating random rewards','Maximizing speed'],correct:1,explanation:'RLHF trains reward model on human comparisons, uses it for PPO fine-tuning to align LLMs.',xp:20},
        {id:'ai-a7',type:'multiple-choice',question:'Catastrophic forgetting?',options:['Forgetting hyperparameters','Network forgets previous tasks when learning new ones','Data corruption','Gradient explosion'],correct:1,explanation:'Networks overwrite previous knowledge. Solutions: EWC, replay buffers, progressive networks.',xp:20},
        {id:'ai-a8',type:'multiple-choice',question:'Advantage of sparse attention?',options:['Higher accuracy','Reducing O(n²) to O(n√n) or O(n log n) for long sequences','Easier training','Better gradients'],correct:1,explanation:'Sparse attention (Longformer) computes over relevant subsets, enabling long sequences.',xp:20},
        {id:'ai-a9',type:'multiple-choice',question:'Neural Architecture Search (NAS)?',options:['Manual design','Automatically discovering optimal architectures using search algorithms or RL','Random architectures','Fixed templates'],correct:1,explanation:'NAS automates architecture design as optimization, though computationally expensive.',xp:20},
        {id:'ai-a10',type:'multiple-choice',question:'Gumbel-Softmax trick?',options:['Image generation','Making discrete sampling differentiable via continuous relaxation','Text preprocessing','Activation function'],correct:1,explanation:'Gumbel-Softmax approximates discrete sampling with continuous differentiable operation.',xp:20},
        {id:'ai-a11',type:'multiple-choice',question:'Meta-learning?',options:['Learning metadata','Training models to quickly adapt to new tasks with few examples','Analyzing logs','Learning hyperparameters only'],correct:1,explanation:'Meta-learning (MAML) learns initialization for quick task adaptation (few-shot).',xp:20},
        {id:'ai-a12',type:'multiple-choice',question:'Diffusion models vs GANs challenge?',options:['Speed','Training stability and mode coverage - no mode collapse','Model size','Data requirements'],correct:1,explanation:'Diffusion models: stable training, better coverage than GANs, but slower sampling.',xp:20},
        {id:'ai-a13',type:'multiple-choice',question:'Classifier-free guidance in diffusion?',options:['Removing classifiers','Controlling generation by training single model to be conditional and unconditional','Speeding inference','Data augmentation'],correct:1,explanation:'Classifier-free guidance interpolates conditional/unconditional predictions for quality.',xp:20},
        {id:'ai-a14',type:'multiple-choice',question:'Double descent phenomenon?',options:['Loss going up twice','Test error decreases, increases (classical), then decreases in overparameterized regime','Two-stage training','Gradient descent twice'],correct:1,explanation:'Double descent shows overparameterized models generalize well, challenging bias-variance tradeoff.',xp:20},
        {id:'ai-a15',type:'multiple-choice',question:'Lottery ticket hypothesis?',options:['Random initialization works','Dense networks contain sparse subnetworks that can train to comparable accuracy','Pruning hurts','Larger is better'],correct:1,explanation:'Lottery ticket: successful training finds sparse subnetwork with favorable initialization.',xp:20},
        {id:'ai-a16',type:'multiple-choice',question:'Main innovation in ViT?',options:['Using CNNs','Treating images as patch sequences and applying pure transformer','Using RNNs','Removing attention'],correct:1,explanation:'ViT processes image patches with transformers, showing CNNs arent necessary for vision.',xp:20},
        {id:'ai-a17',type:'multiple-choice',question:'Scaling laws in LLMs?',options:['Performance is random','Performance improves predictably with model/data/compute size following power laws','Bigger is worse','Size doesnt matter'],correct:1,explanation:'Scaling laws show loss decreases predictably with scale, guiding size trade-offs.',xp:20},
        {id:'ai-a18',type:'multiple-choice',question:'Emergent behavior in large models?',options:['Bugs','Abilities appearing suddenly at certain scales (few-shot, reasoning) not in smaller models','Training errors','Data leakage'],correct:1,explanation:'Emergent abilities like chain-of-thought appear unpredictably at scale, suggesting phase transitions.',xp:20},
        {id:'ai-a19',type:'multiple-choice',question:'Purpose of Flash Attention?',options:['Making lights blink','IO-aware attention reducing memory reads/writes, enabling longer contexts','Faster GPUs','New hardware'],correct:1,explanation:'Flash Attention optimizes at hardware level by fusing operations, minimizing HBM access.',xp:20},
        {id:'ai-a20',type:'multiple-choice',question:'Key principle behind World Models in RL?',options:['Model-free only','Learning internal model of environment dynamics to enable planning in latent space','Random exploration','Supervised only'],correct:1,explanation:'World Models learn compressed environment dynamics, enabling policy training in imagination.',xp:20}
      ]
    }
  }
);

// Save AI/ML
fs.writeFileSync(path.join(__dirname, 'data', 'ai-ml.json'), JSON.stringify(aiml, null, 2));
console.log('✅ AI/ML domain created (60 questions)');

